---
version: 2
jobs:
  build:
    docker:
      - image: googleapis/git
    steps:
      - checkout
      - run:
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              git remote add private https://googleapis-publisher:${GITHUB_TOKEN}@github.com/googleapis/googleapis-private.git
              git push private HEAD:master
            fi
    working_directory: /var/code/googleapis/
 

workflows:
  version: 2
  smoketests:
    jobs:
      - smoke-all:
          filters:
            branches:
              only: master
